import os
from fpdf import FPDF
from docx import Document
from docx.shared import Pt, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH
from datetime import datetime

OUTPUTS_DIR = os.path.join(os.path.dirname(__file__), "..", "outputs")


# ── Main export function ───────────────────────────────────────
def export_documents(mom_json: dict, session_id: str) -> tuple:
    """
    Generates PDF and DOCX from MoM JSON.
    Returns (pdf_url, docx_url) as relative paths.
    """
    os.makedirs(OUTPUTS_DIR, exist_ok=True)

    pdf_path  = os.path.join(OUTPUTS_DIR, f"{session_id}.pdf")
    docx_path = os.path.join(OUTPUTS_DIR, f"{session_id}.docx")

    _generate_pdf(mom_json, pdf_path)
    _generate_docx(mom_json, docx_path)

    return f"/outputs/{session_id}.pdf", f"/outputs/{session_id}.docx"


# ── Delete files after download ────────────────────────────────
def delete_documents(session_id: str):
    for ext in ["pdf", "docx"]:
        path = os.path.join(OUTPUTS_DIR, f"{session_id}.{ext}")
        if os.path.exists(path):
            os.remove(path)


# ══ PDF Generation ═════════════════════════════════════════════
def _generate_pdf(mom: dict, path: str):

    pdf = FPDF()
    pdf.add_page()
    pdf.set_margins(20, 20, 20)
    pdf.set_auto_page_break(auto=True, margin=20)

    # ── Title ──────────────────────────────────────────────────
    pdf.set_font("Helvetica", "B", 18)
    pdf.set_text_color(26, 26, 40)
    pdf.cell(0, 12, mom.get("title", "Minutes of Meeting"), ln=True, align="C")

    # ── Date ───────────────────────────────────────────────────
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(100, 100, 100)
    pdf.cell(0, 8, f"Date: {mom.get('date', datetime.now().strftime('%Y-%m-%d'))}", ln=True, align="C")
    pdf.ln(4)

    # ── Divider ────────────────────────────────────────────────
    pdf.set_draw_color(200, 200, 200)
    pdf.line(20, pdf.get_y(), 190, pdf.get_y())
    pdf.ln(6)

    # ── Participants ───────────────────────────────────────────
    _pdf_section(pdf, "Participants")
    participants = mom.get("participants", [])
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(50, 50, 50)
    pdf.multi_cell(0, 7, ", ".join(participants) if participants else "—")
    pdf.ln(4)

    # ── Agenda ─────────────────────────────────────────────────
    _pdf_section(pdf, "Agenda")
    for item in mom.get("agenda", []):
        _pdf_bullet(pdf, item)
    pdf.ln(2)

    # ── Key Discussions ────────────────────────────────────────
    _pdf_section(pdf, "Key Discussions")
    for item in mom.get("discussions", []):
        _pdf_bullet(pdf, item)
    pdf.ln(2)

    # ── Decisions ──────────────────────────────────────────────
    _pdf_section(pdf, "Decisions")
    for item in mom.get("decisions", []):
        _pdf_bullet(pdf, item)
    pdf.ln(2)

    # ── Action Items ───────────────────────────────────────────
    _pdf_section(pdf, "Action Items")
    for item in mom.get("action_items", []):
        owner    = item.get("owner", "—")
        task     = item.get("task", "—")
        deadline = item.get("deadline", "—")
        line     = f"{owner}  —  {task}  (by {deadline})"
        _pdf_bullet(pdf, line)

    # ── Footer ─────────────────────────────────────────────────
    pdf.set_y(-20)
    pdf.set_font("Helvetica", "I", 8)
    pdf.set_text_color(150, 150, 150)
    pdf.cell(0, 8, "Generated by MoM Generator", align="C")

    pdf.output(path)


def _pdf_section(pdf: FPDF, title: str):
    pdf.set_font("Helvetica", "B", 12)
    pdf.set_text_color(30, 30, 60)
    pdf.cell(0, 10, title, ln=True)
    pdf.set_draw_color(83, 74, 183)
    pdf.line(20, pdf.get_y(), 80, pdf.get_y())
    pdf.ln(3)


def _pdf_bullet(pdf: FPDF, text: str):
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(50, 50, 50)
    pdf.cell(6, 7, "-", ln=False)
    pdf.multi_cell(0, 7, text)


# ══ DOCX Generation ════════════════════════════════════════════
def _generate_docx(mom: dict, path: str):

    doc = Document()

    # ── Page margins ───────────────────────────────────────────
    for section in doc.sections:
        section.top_margin    = Pt(50)
        section.bottom_margin = Pt(50)
        section.left_margin   = Pt(70)
        section.right_margin  = Pt(70)

    # ── Title ──────────────────────────────────────────────────
    title_para = doc.add_paragraph()
    title_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = title_para.add_run(mom.get("title", "Minutes of Meeting"))
    run.bold      = True
    run.font.size = Pt(18)
    run.font.color.rgb = RGBColor(26, 26, 40)

    # ── Date ───────────────────────────────────────────────────
    date_para = doc.add_paragraph()
    date_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
    date_run = date_para.add_run(
        f"Date: {mom.get('date', datetime.now().strftime('%Y-%m-%d'))}"
    )
    date_run.font.size = Pt(10)
    date_run.font.color.rgb = RGBColor(100, 100, 100)

    doc.add_paragraph()

    # ── Participants ───────────────────────────────────────────
    _docx_heading(doc, "Participants")
    participants = mom.get("participants", [])
    doc.add_paragraph(", ".join(participants) if participants else "—")

    # ── Agenda ─────────────────────────────────────────────────
    _docx_heading(doc, "Agenda")
    for item in mom.get("agenda", []):
        _docx_bullet(doc, item)

    # ── Key Discussions ────────────────────────────────────────
    _docx_heading(doc, "Key Discussions")
    for item in mom.get("discussions", []):
        _docx_bullet(doc, item)

    # ── Decisions ──────────────────────────────────────────────
    _docx_heading(doc, "Decisions")
    for item in mom.get("decisions", []):
        _docx_bullet(doc, item)

    # ── Action Items ───────────────────────────────────────────
    _docx_heading(doc, "Action Items")
    for item in mom.get("action_items", []):
        owner    = item.get("owner", "—")
        task     = item.get("task", "—")
        deadline = item.get("deadline", "—")
        _docx_bullet(doc, f"{owner}  —  {task}  (by {deadline})")

    # ── Footer ─────────────────────────────────────────────────
    footer = doc.sections[0].footer
    footer_para = footer.paragraphs[0]
    footer_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
    footer_run = footer_para.add_run("Generated by MoM Generator")
    footer_run.font.size = Pt(8)
    footer_run.font.color.rgb = RGBColor(150, 150, 150)

    doc.save(path)


def _docx_heading(doc: Document, title: str):
    para = doc.add_paragraph()
    run  = para.add_run(title)
    run.bold           = True
    run.font.size      = Pt(12)
    run.font.color.rgb = RGBColor(30, 30, 60)
    doc.add_paragraph()


def _docx_bullet(doc: Document, text: str):
    para = doc.add_paragraph(style="List Bullet")
    run  = para.add_run(text)
    run.font.size = Pt(10)